version: "3.4"
services:
  portfolio:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "3000:3000"
    networks:
      - production-network
networks:
  production-network:
    name: production-network
    external: true